# Generated by Django 5.2 on 2025-06-14 08:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_userprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietchange',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dietchange',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietchange',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_changes', to='frontend.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='loyalty_points_refunded',
            field=models.IntegerField(default=0, help_text='Liczba zwróconych punktów lojalnościowych'),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dodatkowe dane w formacie JSON'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Opłata za subskrypcję'), ('adjustment', 'Dopłata za zmianę'), ('refund', 'Zwrot'), ('partial_refund', 'Częściowy zwrot')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_type',
            field=models.CharField(blank=True, choices=[('money', 'Pieniądze'), ('points', 'Punkty lojalnościowe')], help_text='Typ zwrotu - pieniądze lub punkty', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietchange',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dopłata (+) lub zwrot (-)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='dietchange',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_changes', to='frontend.subscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Ujemna wartość dla zwrotów', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('processing', 'Przetwarzana'), ('completed', 'Zakończona'), ('failed', 'Nieudana'), ('refunded', 'Zwrócona'), ('partial_refund', 'Częściowy zwrot')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(help_text='W symulacji: SIM_PAY_{UUID}', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='frontend.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='W symulacji: SIM_CUS_{user_id}', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='W symulacji: SIM_SUB_{UUID}', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'status'], name='frontend_pa_subscri_ee057f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='frontend_pa_stripe__2a82b9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='frontend_pa_payment_44181b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='frontend_pa_payment_356414_idx'),
        ),
    ]
