# Generated by Django 5.2 on 2025-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_dietchange_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diet_plans/'),
        ),
    ]
